"""Builds the MakeHuman crowd as textured characters, as the cast is built (run with plain Python, not Blender):

  python scripts/blender/human_figures.py [name or part of a name ...] [--jobs 3] [--force]

The figures are the dressed ones listed in scripts/blender/mob_figures.json (the same bodies, hair and clothes the
mob's converted figures in assets/mob/ were made from; the nude body types are left out). For each, a character
definition is written to debug-shots/humans/defs/<name>.json and built by build_character.py, the salaryman's and
the maid's pipeline: the skin graded and smoothed, the hair recoloured black, dark brown or grey by age, the
clothes as their assets come, everything on the game_engine rig. The result is assets/humans/<name>.glb, for the
test page humans.html (src/poc3d/humans/). No previews are rendered, so nothing here uses the GPU.

A figure whose GLB is newer than the list is skipped unless --force. --jobs runs that many Blenders at once.
BLENDER in the environment names another blender.exe.
"""
import json
import os
import subprocess
import sys
import zlib
from concurrent.futures import ThreadPoolExecutor

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
BLENDER = os.environ.get('BLENDER', r'C:\Program Files\Blender Foundation\Blender 5.2\blender.exe')
LIST = os.path.join(REPO, 'scripts', 'blender', 'mob_figures.json')
DEFS = os.path.join(REPO, 'debug-shots', 'humans', 'defs')
OUT = os.path.join('assets', 'humans')

# Hair by age: black or dark brown, greying from the late fifties, grey from the late sixties.
DARK = ['#141210', '#141210', '#18130f', '#22180f']
GREYING = '#3a3836'
GREY = '#8a8884'
# The most triangles a garment or a hair asset keeps (a pair of flats comes with 57,000).
MAX_TRIS = {'clothes': 7000, 'hair': 6000}


def definition(fig):
    """A build_character.py definition for a figure of the list."""
    name = fig['name']
    b = fig['body']
    male = b.get('gender', 1) >= 0.5
    years = b.get('years', 30)
    sex = 'male' if male else 'female'
    pick = zlib.crc32(name.encode())
    hair = fig.get('hair', 'none')
    body = {'gender': b.get('gender', 1), 'years': years, 'race': {'asian': 1}, 'targets': fig.get('targets', {}), 'decimate': 0.6}
    if 'height-cm' in b:
        body['height_cm'] = b['height-cm']
    for macro in ('muscle', 'weight', 'proportions', 'cupsize', 'firmness'):
        if macro in b:
            body[macro] = b[macro]
    skin_ops = [{'op': 'grade', 'saturation': 0.8, 'gamma': 0.96}, {'op': 'smooth', 'radius': 2, 'amount': 0.4 if male else 0.5}]
    color = GREY if years >= 68 else GREYING if years >= 57 else DARK[pick % len(DARK)]
    d = {
        'name': name,
        'about': 'Generated by scripts/blender/human_figures.py from scripts/blender/mob_figures.json.',
        'out': os.path.join(OUT, name + '.glb').replace('\\', '/'),
        'body': body,
        'max_tex': 512,
        'skin': {'asset': ('old_' if years >= 62 else 'middleage_' if years >= 40 else 'young_') + 'asian_' + sex, 'max_tex': 1024, 'roughness': 0.55, 'ops': skin_ops},
        'eyes': {'asset': 'high-poly', 'color': 'brown', 'max_tex': 256, 'roughness': 0.35, 'ops': [{'op': 'grade', 'sat': [0.15, 1], 'saturation': 0.55, 'gain': [0.55, 0.5, 0.48]}]},
        'eyebrows': {'asset': 'eyebrow009' if male else 'eyebrow001', 'max_tex': 256, 'double_sided': True},
        'eyelashes': {'asset': 'eyelashes01', 'max_tex': 256, 'double_sided': True},
        'clothes': [{'asset': c, 'roughness': 0.85, 'metallic': 0, 'max_tris': MAX_TRIS['clothes']} for c in fig.get('clothes', [])],
    }
    if hair != 'none':
        # (The scalp under the hair darkened to its colour, so a hair asset's ragged edge doesn't show skin.)
        skin_ops.append({'op': 'colorize', 'color': color, 'contrast': 0.5, 'uvmask': 'under_hair', 'amount': 0.9})
        d['hair'] = {'asset': hair, 'roughness': 0.6, 'double_sided': True, 'normal_map': False, 'max_tris': MAX_TRIS['hair'], 'ops': [{'op': 'colorize', 'color': color, 'contrast': 0.8}]}
    return d


def build(fig):
    name = fig['name']
    path = os.path.join(DEFS, name + '.json')
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(definition(fig), f, indent=2)
    out = subprocess.run([BLENDER, '-b', '--python', os.path.join('scripts', 'blender', 'build_character.py'), '--', path], capture_output=True, text=True, cwd=REPO)
    text = out.stdout + out.stderr
    done = [line for line in text.splitlines() if line.startswith('CHARACTER_GLB')]
    if not done or 'Traceback' in text or out.returncode != 0:
        tail = [line for line in text.splitlines() if line.strip()][-6:]
        return name, None, '\n   '.join(tail)
    report = next((json.loads(line[len('CHARACTER_REPORT '):]) for line in text.splitlines() if line.startswith('CHARACTER_REPORT ')), {})
    return name, '%s  %d triangles' % (done[0][len('CHARACTER_GLB '):], report.get('triangles', 0)), None


def main():
    argv = sys.argv[1:]
    jobs = int(argv[argv.index('--jobs') + 1]) if '--jobs' in argv else 3
    force = '--force' in argv
    only = [a for i, a in enumerate(argv) if not a.startswith('--') and (i == 0 or argv[i - 1] != '--jobs')]
    with open(LIST, encoding='utf-8') as f:
        figures = [fig for fig in json.load(f)['figures'] if fig.get('clothes')]
    os.makedirs(DEFS, exist_ok=True)
    os.makedirs(os.path.join(REPO, OUT), exist_ok=True)
    todo = []
    for fig in figures:
        if only and not any(o in fig['name'] for o in only):
            continue
        glb = os.path.join(REPO, OUT, fig['name'] + '.glb')
        if not force and os.path.exists(glb) and os.path.getmtime(glb) > os.path.getmtime(LIST):
            continue
        todo.append(fig)
    print('building %d of %d figures, %d at a time' % (len(todo), len(figures), jobs), flush=True)
    failed = []
    with ThreadPoolExecutor(max_workers=jobs) as pool:
        for name, done, err in pool.map(build, todo):
            if err:
                failed.append(name)
                print('FAILED', name, '\n   ' + err, flush=True)
            else:
                print(done, flush=True)
    if failed:
        print('FAILED:', ' '.join(failed))


if __name__ == '__main__':
    main()
