import { chromium } from 'playwright-core';
import { shotServer } from '../scripts/shotServer.mjs';
const out = process.argv[2];
const server = await shotServer({ server: { port: 0 }, logLevel: 'silent' });
await server.listen();
const browser = await chromium.launch({ channel: 'msedge', headless: true, args: ['--use-angle=d3d11', '--enable-gpu', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 1000, height: 650 } });
page.on('pageerror', (e) => console.log('PAGEERROR', String(e)));
await page.goto(`${server.resolvedUrls.local[0]}models.html?fp=1`);
await page.waitForFunction(() => window.__fp && window.__fp.rig(), null, { timeout: 60000, polling: 250 });
await page.waitForTimeout(1500);
await page.evaluate(() => { document.getElementById('panel').style.display = 'none'; document.querySelectorAll('.label').forEach((l) => (l.style.display = 'none')); });
await page.evaluate(async () => { await __fp.enter(14, 24, 0); __fp.kind('lever'); __fp.oneHand(true); __fp.aim(true); __fp.look(0, 0); });
await page.waitForTimeout(1200);
console.log(await page.evaluate(() => {
  const rig = __fp.rig(); const arm = rig.arms.r; const V = arm.hand.position.constructor;
  const S = arm.upper.getWorldPosition(new V()), E = arm.lower.getWorldPosition(new V()), H = arm.hand.getWorldPosition(new V());
  const a = E.clone().sub(S).normalize(), b = H.clone().sub(E).normalize();
  return `reach ${(S.distanceTo(H) * 100).toFixed(1)} of ${((arm.lenA + arm.lenB) * 100).toFixed(1)} cm, elbow bend ${(Math.acos(Math.min(1, a.dot(b))) * 180 / Math.PI).toFixed(1)} deg`;
}));
await page.screenshot({ path: `${out}/e1_fp.png` });
await page.evaluate(() => __fp.look(0, 0.35));
await page.waitForTimeout(800);
await page.screenshot({ path: `${out}/e2_fp_up.png` });
await page.evaluate(() => __fp.look(0, 0));
await page.waitForTimeout(800);
const view = async (name, f) => { await page.evaluate(f); await page.waitForTimeout(400); await page.screenshot({ path: `${out}/${name}.png` }); };
await page.evaluate(() => __fp.freeze(true));
await view('e3_side', () => { const c = __fp.rig().object.children[0].position; __view(c.x + 2.0, 3.0, c.z - 0.4, c.x + 0.1, 1.2, c.z - 0.5); });
await view('e4_front', () => { const c = __fp.rig().object.children[0].position; __view(c.x + 1.6, 2.6, c.z + 1.6, c.x + 0.1, 1.3, c.z - 0.5); });
await page.evaluate(() => { __fp.freeze(false); __fp.look(0, 0.35); });
await page.waitForTimeout(800);
await page.evaluate(() => __fp.freeze(true));
await view('e5_side_up', () => { const c = __fp.rig().object.children[0].position; __view(c.x + 2.0, 3.0, c.z - 0.4, c.x + 0.1, 1.4, c.z - 0.5); });
await browser.close(); await server.close();
