import { launchBrowser } from '../scripts/launchBrowser.mjs';
import { shotServer } from '../scripts/shotServer.mjs';
const out = process.argv[2];
const server = await shotServer({ server: { port: 0 }, logLevel: 'silent' });
await server.listen();
const base = server.resolvedUrls.local[0];
const browser = await launchBrowser({ channel: 'msedge', headless: true, args: ['--use-angle=d3d11', '--enable-gpu', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
page.on('pageerror', (e) => console.log('PAGEERROR', String(e)));
page.on('console', (m) => { if (m.type() === 'error' || m.type() === 'warning') console.log('CONSOLE', m.text().slice(0, 300)); });
await page.goto(`${base}models.html?fp=1`);
await page.waitForFunction(() => window.__fp && window.__fp.rig(), null, { timeout: 40000, polling: 250 });
await page.waitForTimeout(2500);
await page.evaluate(() => { document.getElementById('panel').style.display = 'none'; });
const shot = async (name, fn, wait = 600) => { await page.evaluate(fn); await page.waitForTimeout(wait); await page.screenshot({ path: `${out}/${name}.png` }); };
await shot('1_low', () => { __fp.kind('lever'); __fp.look(0, -0.05); });
await shot('2_aim', () => { __fp.aim(true); });
await shot('3_down', () => { __fp.aim(false); __fp.look(0, -1.1); });
await shot('4_double_aim', () => { __fp.kind('double'); __fp.look(0, 0); __fp.aim(true); });
await shot('5_lever_thrown', () => { __fp.kind('lever'); __fp.aim(true); }, 500);
await page.evaluate(() => __fp.fire()); await page.waitForTimeout(300); await page.screenshot({ path: `${out}/5_lever_thrown.png` });
await shot('10_walk_down', () => { __fp.aim(false); __fp.look(0, -0.85); __fp.walk(true); }, 700);
await page.evaluate(() => __fp.walk(false));
// From outside: freeze the pose, look from the side and front.
await page.evaluate(() => { __fp.aim(true); __fp.look(0, 0); });
await page.waitForTimeout(600);
await page.evaluate(() => { __fp.freeze(true); const c = __fp.rig().object.children[0].position; window.__c = [c.x, c.z]; __view(c.x + 1.6, 1.6, c.z - 0.4, c.x, 1.3, c.z - 0.3); });
await page.waitForTimeout(400); await page.screenshot({ path: `${out}/6_side.png` });
await page.evaluate(() => { const [x, z] = window.__c; __view(x + 0.5, 1.7, z - 1.6, x, 1.35, z - 0.2); });
await page.waitForTimeout(400); await page.screenshot({ path: `${out}/7_front.png` });
await page.evaluate(() => { const g = __fp.rig().guns.lever.root.position; __view(g.x - 0.25, g.y + 0.12, g.z - 0.45, g.x, g.y - 0.03, g.z - 0.08); });
await page.waitForTimeout(400); await page.screenshot({ path: `${out}/8_hands.png` });
await page.evaluate(() => { const g = __fp.rig().guns.lever.root.position; __view(g.x + 0.3, g.y - 0.05, g.z - 0.3, g.x, g.y - 0.03, g.z - 0.08); });
await page.waitForTimeout(400); await page.screenshot({ path: `${out}/9_hands_right.png` });
await browser.close();
await server.close();
